<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NewLogin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>737fdeb6-ecd8-4175-a784-21ee15732637</testSuiteGuid>
   <testCaseLink>
      <guid>8d069c9b-a7ab-4c91-856d-f863a783131b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NewLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ae72767c-2b72-494b-a3b6-10f2cec31a91</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-5</value>
         </iterationEntity>
         <testDataId>Data Files/TestCaseLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ae72767c-2b72-494b-a3b6-10f2cec31a91</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>account</value>
         <variableId>8c890a98-a17a-4e0f-84d0-71dd68e34bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ae72767c-2b72-494b-a3b6-10f2cec31a91</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>7bfb0862-cd89-466c-abca-60d04c153baa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
