<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Suite_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>41664fb8-8392-456f-9128-ff184a04b471</testSuiteGuid>
   <testCaseLink>
      <guid>91680a1b-85db-42d6-98ae-026768687af4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login_Hutech_Test_Case</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>25f535aa-a960-49a7-9c5d-1a2935613514</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login_Hutech</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>25f535aa-a960-49a7-9c5d-1a2935613514</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>account</value>
         <variableId>94730efe-2f2a-46f8-9e3b-41111f466393</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>25f535aa-a960-49a7-9c5d-1a2935613514</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f704f20e-8aff-4956-bcdc-4f3ecad2db11</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
