<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng nhp</name>
   <tag></tag>
   <elementGuidId>255c83ea-747f-40de-98de-e4140e29e778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.d-lg-none.red-btn.mobile-login.btn.btn-danger.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/nav/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Đăng nhập&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>367b2305-2dc3-4b23-9886-273825a6decc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/authn/login?next</value>
      <webElementGuid>2645629a-6b5d-4f5e-99e5-305a63f9fddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-lg-none red-btn mobile-login btn btn-danger btn-sm</value>
      <webElementGuid>6dcef652-d34c-40f2-aad1-7931941faef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập</value>
      <webElementGuid>66b94362-4ed6-43cb-8920-41c7b3754203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/main[1]/nav[@class=&quot;px-4 nav-wrapper navbar navbar-expand-lg navbar-light&quot;]/a[@class=&quot;d-lg-none red-btn mobile-login btn btn-danger btn-sm&quot;]</value>
      <webElementGuid>03f4aede-8e21-40fd-857a-8feecda3280b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/nav/a</value>
      <webElementGuid>a83f83f0-bab1-4765-9c59-9efbb7ffe7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng nhập')]</value>
      <webElementGuid>2b0569f2-e4b9-4a44-bc32-452c55ada5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/preceding::a[1]</value>
      <webElementGuid>42305cd8-af0b-4f08-abf4-33d088a35d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khóa học'])[1]/preceding::a[2]</value>
      <webElementGuid>60540d32-8284-4634-a8aa-8af046186c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng nhập']/parent::*</value>
      <webElementGuid>4fe48b10-0d53-4204-adfe-cc67be9dcf3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/authn/login?next')]</value>
      <webElementGuid>f0f5f22e-8d84-4797-a32b-e9d3e2415a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ca97ea77-b569-4e37-af7a-deb1ef4260f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/authn/login?next' and (text() = 'Đăng nhập' or . = 'Đăng nhập')]</value>
      <webElementGuid>62109c53-ac4e-42d2-a12e-816fb9fde2f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
