<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_search</name>
   <tag></tag>
   <elementGuidId>c61b1a14-5e30-412f-8667-ffc0eaefb20d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pgn__searchfield_wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/header/div/div/div/div[4]/div/form/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^search$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d289d690-bf2b-41e4-96e2-f82c93ce6563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pgn__searchfield_wrapper</value>
      <webElementGuid>ed225699-ba66-4ac8-84ef-126edb0fb9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b4d3dc29-fc19-4532-a433-35f888ee1ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/main[1]/header[1]/div[@class=&quot;banner container&quot;]/div[@class=&quot;text-over&quot;]/div[@class=&quot;text-wrapper&quot;]/div[@class=&quot;search-area&quot;]/div[@class=&quot;pgn__searchfield d-flex has-focus pgn__searchfield--external&quot;]/form[@class=&quot;pgn__searchfield-form&quot;]/div[@class=&quot;pgn__searchfield_wrapper&quot;]</value>
      <webElementGuid>ad526848-b993-4a4f-9d0f-cbf39a727816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/header/div/div/div/div[4]/div/form/div</value>
      <webElementGuid>cd6e317b-78b3-49e4-8d38-a22eb0b18ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HUTECH'])[1]/following::div[3]</value>
      <webElementGuid>4bab7715-619e-47d1-af77-c7d2ac4393a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='học tập trực tuyến'])[1]/following::div[4]</value>
      <webElementGuid>9202a6dc-b1af-4f28-a51c-7212c2835e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/form/div</value>
      <webElementGuid>0cfcb5af-e070-42f0-8a06-78f1b019cc3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'search' or . = 'search')]</value>
      <webElementGuid>952696df-36b9-4fbe-bb87-f133696dca41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
